{{- if .Values.geminiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: gemini-api-key-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  api-key: {{ .Values.geminiApiKey | b64enc | quote }}
{{- end }}
